name: deploy
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - develop
      - master
env:
  # jdk-version: openjdk@~1.15.0
  project-name: 2PPy
  workflow: deploy
  # gradle-options: "--no-daemon --console=plain --stacktrace"
jobs:
  deploy-on-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        run: | 
          python --version
          pip --version
          java --version
          javac --version

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - name: Get All Tags
        run: git fetch --tags -f

      - name: Restore Python dependencies
        run: pip install -r requirements.txt

      - name: Restore JVM dependencies
        run: ./download-jars.sh

      - name: Test
        run: python -m unittest

      - name: Pack
        run: python -m build

      - name: Archive Dist Artifacts
        if: failure() || success()
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: './dist'

      - name: Upload
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERANAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
